### ISSUE TITLE
Finding a Name for The App

### ISSUE THREAD

**Issue by tajmone** [tajmone/PBCodeArcProto#1]
Currently, the application that will build the website for the [PureBasic-CodeArchive-Rebirth] project is being referenced as __"The Indexer"__. We need to find a better name for it.

__"WebsiteBuilder"__ would seem an obvious choice, but maybe something less impersional and abstract could be a better choice.

[PureBasic-CodeArchive-Rebirth]: PureBasic-CodeArchive-Rebirth "Visit the PureBasic-CodeArchive-Rebirth project"

**Comment by SicroAtGit** [comment]
"HTMLPagesCreator"? The name indicates much more what the program does.

**Comment by tajmone** [comment]
Deal! "HTMLPagesCreator" is straight to the point and also covers local browsing (which isn't the same as a website, since there is no WWW involved).
