### ISSUE TITLE
Permission & License for Old Tools

### ISSUE THREAD

**Issue by tajmone** [tajmone/PBCodeArcProto#16]
@SicroAtGit, I need your permission and a License to adapt the old tools to the new workflow — ie, the two files which I've placed in [`_tempwork` folder][tempwork]:

- [`CodesChecker.pb`][Checker.pb]
- [`CodesCleaner.pb`][Cleaner.pb]

I couldn't find a license mentioned in the source, nor in the root of the original dev branch where they were taken from. I remember that once in an email you mentioned that all your code in that project was reusable, but here a proper licensing might be more appropriate.

As I'm modularizing the code, I would like to create a dedicate module to deal with resources validation and cleaning, and could reuse parts of the old tools that deal with checks that I haven't covered, and integrate them with the new header comments system.

This should also allow me to create a new version of these tools, using the shared modules, and have a chance to test how the modules work in different usages.

If you could declare them MIT it would make it easy to integrate with the rest of the code, and I'd only have to add my name on top.

Thanks

[tempwork]: https://github.com/tajmone/PBCodeArcProto/tree/master/_tempwork

[Checker.pb]: https://github.com/tajmone/PBCodeArcProto/tree/master/_tempwork/CodesChecker.pb
[Cleaner.pb]: https://github.com/tajmone/PBCodeArcProto/tree/master/_tempwork/CodesCleaner.pb

**Comment by SicroAtGit** [comment]
After lunch I will add the MIT license to these codes and upload the new codes.

> I couldn't find a license mentioned in the source, nor in the root of the original dev branch where they were taken from. I remember that once in an email you mentioned that all your code in that project was reusable, but here a proper licensing might be more appropriate.

The license is missing for these codes, because they are officially no longer existing since the repository was rebuilt. Only the outdated forks of the repository still have the codes included, as you can see.

I hope to find more time this weekend to continue working on the project.

**Comment by tajmone** [comment]
Thanks. Don't worry about the time; this projects is going to take a while to get finished, the important thing is to get it done nicely, and produce some tools that are well documented, easy to use and maintain with future versions of PB.

So far things are looking great, by joining our perspectives and experiences we've managed to work out a nice solution for maintaining both the codes and the website. I can see that the original tools were a good idea, and it's worth recreating them.

The whole idea is that these tools should make the CodeArchiv a robust reference for PB source codes and tools, and I believe that with these tools in place it will definitely end up being both a good website as well as a local resources archive. And I'm optimistic that people will be happy to store their projects in a well structured archive like this one.

I can also see that the modular design approach, along with a well thought API, will allow creating more tools in the future to further improve functionality of the project. So I realize that getting the initial codebase right is crucial, even if it means that the App won't be ready as soon as expected. 

Maybe in the future we'll manage to create a Git abstraction layer too, to simplify contributing code to the repository ... that would be cool, especially if it provided some GUI.

**Comment by tajmone** [comment]
Thanks.

I suggest that in the copyright line we also add the CodeArchive URL. Since the MIT only oblies to reproduces the original copyright line(s), we could at least be sure that any derivative project (eve if closed source) will provide a link back to the original project.

You can put basically anything you want in the copyright line. Usually people add an email, or their website URL, anything that could trace the copyright line back to original dev's website and works. — I've seen some people add a link to a website where they sell products, as a way to get potential income from people that would visit the link, even though the license had nothing to do with that website; there is nothing wrong with that, a little advertising as a clause to reusing free code.

**Comment by SicroAtGit** [comment]
Yes, any information can be added to the copyright line to ensure that anyone can contact the real author.

You're right, only my nickname is not enough. I have revised my copyright notice.

**Comment by SicroAtGit** [comment]
Do you miss anything else or can the issue be closed?
