### ISSUE TITLE
Create a GUI or Console App?

### ISSUE THREAD

**Issue by tajmone** [tajmone/PBCodeArcProto#2]
I'm still not sure if the website builder should be a GUI or console app.

The pros and cons of each choice should be considered, but maybe we're still at an early stage to do that.

A GUI app would definitely allow easier acess to configuration files, tracking new/updated resources and targetting single resources previews. But building a GUI will add quite some work.

Currently, the app is intended to be simply run from PureBASIC IDE, which has the advantages of exploting the debugger window to display output. It might just as well remain so, since it's intended to be used mainly by the proejct's maintainers; but then, with little effort it could be turned into a console app as well.

**Comment by SicroAtGit** [comment]
I have designed my existing repo-dev-tools which I created for the code-archive in such a way that they must be started directly from the code within the PB-IDE. That's quite enough. The repo tools shouldn't be beautiful, but only do what they were created for. More is only a waste of time with these tools.
